version: "3"

networks:
  backend:


services:
  oneFrame:
    container_name: one_frame
    image: paidyinc/one-frame
    networks:
      - backend

  api:
    container_name: forex_proxy_api
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - API_PORT=8000
      - ONE_FRAME_HOST_NAME=oneFrame
      - ONE_FRAME_PORT=8080
    networks:
      - backend
    ports:
      - "8000:8000"
    depends_on:
      - oneFrame
